import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class GridViewOrnek extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(title: Text("GridView"),),
      body: GridView.builder(
        gridDelegate:
            SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
        itemBuilder: (BuildContext context, int index) {
          return GestureDetector(
            child: Container(
              alignment: Alignment.bottomCenter,
              decoration: BoxDecoration(
                  border: Border.all(
                      color: Colors.pink, width: 5, style: BorderStyle.solid),
                  //borderRadius: BorderRadius.all(Radius.circular(5.0)),
                  boxShadow: [
                    BoxShadow(
                        color: Colors.red,
                        offset: Offset(10.0, 5.0),
                        blurRadius: 10.0)
                  ],
                  shape: BoxShape.circle,
                  color: Colors.teal[100 * ((index + 1) % 8)],
                  gradient: LinearGradient(
                      colors: [Colors.yellow, Colors.blue],
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter),
                  image: DecorationImage(
                      image: AssetImage("images/Loading.gif"),
                      fit: BoxFit.contain)),
              child: Text(
                "Merhaba Flutter $index",
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 21, color: Colors.deepOrange),
              ),
              margin: EdgeInsets.all(20),
            ),
            onTap: ()=>debugPrint("merhaba flutter $index tıklanıldı"),
            onDoubleTap: ()=>debugPrint("merhaba flutter $index çift tıklanıldı"),
            onLongPress: ()=>debugPrint("merhaba flutter $index uzun basıldı"),
            onHorizontalDragStart: (e)=>debugPrint("merhaba flutter $index tıklanıldıasd $e"),
          );
        },
      ),
    );
  }
}

//GridView.extent(
//      maxCrossAxisExtent: 200,
//    primary: false,
//      padding: EdgeInsets.all(10),
//      crossAxisSpacing: 20,
//      mainAxisSpacing: 40,
//      scrollDirection: Axis.horizontal,
//      children: <Widget>[
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//      ],
//    );

//GridView.count(
//      crossAxisCount: 6,
//    primary: false,
//      padding: EdgeInsets.all(10),
//      crossAxisSpacing: 20,
//      mainAxisSpacing: 40,
//      scrollDirection: Axis.horizontal,
//      children: <Widget>[
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//        Container( color: Colors.teal[300],
//          child: Text("Merhaba Flutter",textAlign: TextAlign.center,),
//          alignment: Alignment.center,
//        ),
//      ],
//    );
